/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.examples.accounts.infra.datamodel;


import io.github.crabzilla.examples.accounts.infra.datamodel.tables.AccountSummary;
import io.github.crabzilla.examples.accounts.infra.datamodel.tables.records.AccountSummaryRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountSummaryRecord> ACCOUNT_SUMMARY_PKEY = UniqueKeys0.ACCOUNT_SUMMARY_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountSummaryRecord> ACCOUNT_SUMMARY_PKEY = Internal.createUniqueKey(AccountSummary.ACCOUNT_SUMMARY, "account_summary_pkey", new TableField[] { AccountSummary.ACCOUNT_SUMMARY.ID }, true);
    }
}
