/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.examples.accounts.infra.datamodel;


import io.github.crabzilla.examples.accounts.infra.datamodel.tables.AccountSummary;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account_summary</code>.
     */
    public static final AccountSummary ACCOUNT_SUMMARY = AccountSummary.ACCOUNT_SUMMARY;
}
