/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.examples.accounts.infra.datamodel.tables.pojos;


import io.github.crabzilla.examples.accounts.infra.datamodel.tables.interfaces.IAccountSummary;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountSummary implements VertxPojo, IAccountSummary {

    private static final long serialVersionUID = -1915871630;

    private Integer    id;
    private BigDecimal balance;

    public AccountSummary() {}

    public AccountSummary(IAccountSummary value) {
        this.id = value.getId();
        this.balance = value.getBalance();
    }

    public AccountSummary(
        Integer    id,
        BigDecimal balance
    ) {
        this.id = id;
        this.balance = balance;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public AccountSummary setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public BigDecimal getBalance() {
        return this.balance;
    }

    @Override
    public AccountSummary setBalance(BigDecimal balance) {
        this.balance = balance;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountSummary (");

        sb.append(id);
        sb.append(", ").append(balance);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAccountSummary from) {
        setId(from.getId());
        setBalance(from.getBalance());
    }

    @Override
    public <E extends IAccountSummary> E into(E into) {
        into.from(this);
        return into;
    }

    public AccountSummary(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
