/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.examples.accounts.infra.datamodel.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAccountSummary extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.account_summary.id</code>.
     */
    public IAccountSummary setId(Integer value);

    /**
     * Getter for <code>public.account_summary.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>public.account_summary.balance</code>.
     */
    public IAccountSummary setBalance(BigDecimal value);

    /**
     * Getter for <code>public.account_summary.balance</code>.
     */
    public BigDecimal getBalance();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IAccountSummary
     */
    public void from(IAccountSummary from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IAccountSummary
     */
    public <E extends IAccountSummary> E into(E into);

    @Override
    public default IAccountSummary fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getInteger("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.Integer",e);
        }
        try {
            // Omitting unrecognized type java.math.BigDecimal for column balance!
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("balance","java.math.BigDecimal",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        // Omitting unrecognized type java.math.BigDecimal for column balance!
        return json;
    }

}
